### ISSUE TITLE
Bladordning?

### ISSUE THREAD

**Issue by Kjagd** [rndfm/elspotpris#104]
Hej, fedt projekt du har her.

Det er lidt sjovt at næsten alle selvskaber har et blad i 'bladordningen', men nærmest ingen tager sig seperat betalt for det.

<img src="https://user-images.githubusercontent.com/1812228/207322033-f39bf8a9-c212-4aa6-a703-d80a604af074.png" width=30% height=30%> 

Er der nogen der ved om de må rulle de ind i spotprisen uden at have opgivet det seperat?
I så fald kunne det jo være en interessant nok parameter at have med, hvis man ellers kunne få noget data på det.

Umiddelbart er det kun Aura som tilbyder at man kan slå det til og fra for 1.56 øre/kWh.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/1812228/207322569-e077acde-a009-43fa-9a00-66d76b812052.png">

https://www.aura.dk/stroem/aura-flexel/

Nettopower/Velkommen har også valgfrihed:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/1812228/207323762-969ddf10-2f5a-4029-9f11-3251c7f48614.png">

**Comment by rndfm** [comment]
Det kan i hvert fald sagtens være en del af spotpris tillægget. F.eks hos Ewii skriver de således:
"Tillæg for certificeret grøn strøm udgør 1,875 øre/kWh inkl. moms"
Det er så det eneste tillæg de har. Så man må gå ud fra at deres gevinst også ligger heri.

**Comment by Kjagd** [comment]
Ja, det virker så lidt underligt at vindstød kan have et spotpris tillæg på 0 eller 30kr om året, hvis certifikaterne virkeligt kostede 1.875 øre/kWh :)

Ifølge denne artikel fra sidste år ligger priser faktisk også på under 1 øre/kWh: https://klimamonitor.dk/nyheder/art8255973/Certifikater-til-gr%C3%B8n-str%C3%B8m-er-en-ren-bogholderi%C3%B8velse

I hvert fald er den her slags greenwashing da ikke med til at gøre priserne lettere at sammenligne.

I princippet burde man jo have en entry for med og uden certifikater for Aura/Nettopower, selvom det måske bare forvirrer mere end det gavner
...

**Comment by rndfm** [comment]
Som det er nu kan vi ikke skille priserne ad.
