### ISSUE TITLE
'Uden netselskab' men *tarif beløb er vist?

### ISSUE THREAD

**Issue by twikedk** [rndfm/elspotpris#106]
Jeg tænker at hvis jeg vælger 'Uden netselskab' så skal *tarif beløb nok være 0.
![Screenshot_2022-12-14_19-05-52](https://user-images.githubusercontent.com/24204069/207674938-1b165074-127c-4de2-9ce8-223cb2be4305.png)

**Comment by rndfm** [comment]
Ja...
Den er vist det kan man kalde i gråzonen. Fordi disse tariffer er ikke afhængige af netselskabet men skal betales af alle (ligesom elafgiften)

**Comment by twikedk** [comment]
Grunden til jeg nævnte det er at jeg lige har fået fingre i nettopower's app og der er tariffer ikke med under el-afgift, så det er nok, som du skriver, lidt af en gråzone hvor de reelt hører til.

**Comment by rndfm** [comment]
Det hører vel under transport. Bare ikke den del som netselskabet står for.

**Comment by rndfm** [comment]
Jeg så udmærket formulering på et elselskabs hjemmeside omkring netop disse priser. (Det sker ellers ikke så tit)

"Prisen for transport i Energinets system"

Måske man kunne lade sig inspirere.

**Comment by rndfm** [comment]
Jeg har lavet en ekstra tænd/sluk knap til generel transport.
