### ISSUE TITLE
[PRODUKT]

### ISSUE THREAD

**Issue by Henrik77** [rndfm/elspotpris#107]
Udfyld felterne nedenunder.
Alle priser uden moms angivet i kroner.    .15 = 0.15 kr = 15 øre.
Hvis der findes yderligere pristillæg eller gebyrer tilføjes det i samme stil.
Bemærk at udregningen ligger samtlige priser sammen. Vil der gøres opmærksom på en ting som der gratis/ikke betales for kan der laves priser og gebyrer med 0 i "amount".

Hvis der står null ved amount bruges spotprisen.

{
    name: "Navn på elselskab og produktnavn",
    prices: [

        {
            name: "andel energi - Variabel pris",
            amount:  Det ser ud til at man ikke længere kan bestille dette produkt. jvf. https://andelenergi.dk/sel/alle-produkter/
            Jeg tænker der er stor risiko for at folk ender på TimeEnergi istedet - så nok bedst kun at have TimeEnergi i listen.
            
           Tak for det fantastiske arbejde - og undskyld den alternative tilbagemelding her.
            
        },
    ],
    fees: [
     
    ]
}

**Comment by rndfm** [comment]
Hej Henrik.

Ja jeg ser også at der bliver lagt tilbud op på facebook som Andel kunder har modtaget om at skifte fra deres nuværende produkt til Time Energi. Det er liiiidt frækt. Og der nævnes bestemt ikke at Time Energi produktet er markant dyrere.

Jeg har markeret produktet "andel energi - Variabel pris" som udgået på elspotpris.dk

Er det ikke fint de begge står der lidt endnu så kunder på andel energi - Variabel pris har en mulighed for at sammenligne inden de tager imod Andel Energi's "flotte tilbud".
