### ISSUE TITLE
[TARIFF] Flow Elnet

### ISSUE THREAD

**Issue by mooboo** [rndfm/elspotpris#111]
Udfyld værdierne i skemaet herunder.
Priserne er i kroner og uden moms.

Udfyld navn, og tariff for lav- og spidslast.

{
        id: "flow_elnet",
        name: "Flow Elnet",
        // Updated 2022-12-20 - https://flow-elnet.dk/priser-regler/aktuelle-priser
        // From 2023-01-01 normal: .2224, peak: .5835
        // From 2023-04-01 normal: .3977, peak: .9521
        normal: .2241,
        peak: .5871
    },

**Comment by rndfm** [comment]
Jeg har tilføjet flow. Tak for det :)
