### ISSUE TITLE
Høj CPU last

### ISSUE THREAD

**Issue by twikedk** [rndfm/elspotpris#114]
De to bar 0 og 1 er hhv. CPU core 0 og 1

Uden netselskab er CPU last moderat men umiddelbart til den høje side:
![Screenshot_1](https://user-images.githubusercontent.com/24204069/209821487-d3e4cf4a-35b1-4a47-951d-d83f1d8b5448.png)

Hvis jeg så vælger RAH C går den amok:
![Screenshot_2](https://user-images.githubusercontent.com/24204069/209821550-750f05b9-7181-48d3-b7bf-5e648b9e69b1.png)

Og jeg troede så det var her problemet lagde men med Nord Energi Net:
![Screenshot_3](https://user-images.githubusercontent.com/24204069/209821634-86a8556b-5291-47da-8126-90d0abfcd8fb.png)

går det hele godt igen, faktisk bedre end uden netselskab...

Så anbefalingen herfra må lyde at hvis man ønsker at spare på energien er Nord Energi Net et rigtigt godt valg.

**Comment by rndfm** [comment]
Jeg har øje på problemet. Jeg håber at komme med en løsning i aften eller i løbet af i morgen.

**Comment by rndfm** [comment]
Så er problemet afværget :)

Jeg prøver lige at arbejde med performance i løbet af i morgen også. Men nu er siden da nogenlunde responsiv.

**Comment by rndfm** [comment]
Kan du prøve at teste siden igen? Den skulle gerne opføre sig pænt nu :)

**Comment by twikedk** [comment]
Det gør den.
