### ISSUE TITLE
Viser ikke alle Transportudgifter

### ISSUE THREAD

**Issue by Casper-O** [rndfm/elspotpris#115]
Der en bug pt, hvorfor kun vises transport udgifter for dele af dagen, fx kan jeg for N1 kun se tiden for 00-17 lige nu

![D3B9AD0B-D9D6-427D-802B-8F8343A2C328](https://user-images.githubusercontent.com/956154/209954375-89c9a52f-20e8-453c-8ae4-cb195d0be58b.png)

Formoder det fordi du sidder og arbejder på projektet lige nu. I fremtiden bør du måske arbejde på en dev Branch eller have stable Branch som sitet køre fra

**Comment by rndfm** [comment]
Ideen er at den viser nuværende transport således at man kan se beregningen af prisen nu og he3. Men det kan måske godt give mening at vise alle sammen. Men skal den så også vise fremtidige tariffer? 1/1 tariffer... 1/4 tariffer.

Måske med en mulighed for at "folde" ud vil det kunne vises.

**Comment by Casper-O** [comment]
Jeg ikk selv tjekket API’et, så ved ikke om API indeholder fremtids priser (sommer/vinter) men alle priser for dagen, bør imo være synlige.

**Comment by rndfm** [comment]
Nuværende døgn tariffer giver mening. Det viste siden også tidligere.

tor. 29. dec. 2022 19.17 skrev Casper Olsen ***@***.***>:

**Comment by rndfm** [comment]
Så fik jeg lavet så tarifferne for nuværende døgn vises. Den time tariff som er aktiv står ud da de andre er tonet ned.
