### ISSUE TITLE
Add Indfødningstarif (indfødning af el) from 2023

### ISSUE THREAD

**Issue by ciprianbiris** [rndfm/elspotpris#119]
A new "netselskab" fee will be added in 2023:
Indfødningstarif (indfødning af el)  5.32 øre / kwh for n1c

Source:
_1. januar 2023 skal producenter af elektricitet som noget nyt betale indfødningstariffer til de lokale elnetselskaber. Indfødningstarifferne er en betaling pr. kWh for at levere el fra bl.a. vindmøller, solceller og kraftvarmeværker ind i distributionsnettet (0,4-60 kV) og videre ud til kunderne._

from: https://n1.dk/priser-og-vilkaar

ps. This new tariff is NOT just for N1. It is for all of them.

Regards,

**Comment by rndfm** [comment]
But only for power delivered back to the grid?

**Comment by ciprianbiris** [comment]
That makes sense. Can be closed.

Regards,
