### ISSUE TITLE
N1 C does not seem to be correct for 2023 [TARIFF]

### ISSUE THREAD

**Issue by Christian-PK** [rndfm/elspotpris#120]
Udfyld værdierne i skemaet herunder.
Priserne er i kroner og uden moms.

Udfyld navn, og tariff for lav- og spidslast.

{
    name: "N1 C",
    normal: .4322,
    peak: 1.0562
}
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/56740426/210169353-c30326b4-1e19-4316-b311-3eedef8c467e.png">

**Comment by Christian-PK** [comment]
Looks light it calculates correct but the specification for peak is left out.
<img width="696" alt="image" src="https://user-images.githubusercontent.com/56740426/210170044-06773499-e2cc-479b-9fd9-a3c0eb8e9140.png">

**Comment by rndfm** [comment]
It's left out of the calculation for current hour as we are not in a peak hour right now.
When in a peak hour the peak tariff is used and shown.

The kl00-24 at 0kr is strange. But that is what N1 is feeding into the datahub right now.
