### ISSUE TITLE
Ledningsbidrag/nettarif N1

### ISSUE THREAD

**Issue by carlk5** [rndfm/elspotpris#125]
Synes der må være fejl i beløbene og tider for 2023 på nettarif til N1 når jeg læser på elspotpris.dk

**Comment by carlk5** [comment]
https://elspotpris.dk/?gclid=Cj0KCQjwkOqZBhDNARIsAACsbfLr6T6_6_lFduE08d7LABJxvNgfcF4cmOMuY3-FV7eWtqrisWVVxZYaAjupEALw_wcB

Skrol ned på linket og find netbidrag til N1. Mærkelige tider og priser.
Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows

Fra: Christian ***@***.***>
Sendt: 4. januar 2023 14:31
Til: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Emne: Re: [rndfm/elspotpris] Ledningsbidrag/nettarif N1 (Issue #125)


Kan du blive mere præcis omkring hvilke fejl du ser?

**Comment by rndfm** [comment]
Jeg har kontrolleret tarifferne som der bliver beregnet efter og de svare overens med dem som N1 oplyser på deres hjemmeside:
https://n1.dk/priser-og-vilkaar

Bemærk at beregningseksemplet på elspotpris.dk kun viser aktive tariffer for den nuværende time. F.eks. er man i lavlast perioden vises kun lavlast tariffen i udregningen.
Dette gøres for at man kan ligge alle tallene sammen i tabellen og så få det korrekte resultat.


Hvis det er noget andet du synes er mærkeligt kan du så ikke blive lidt mere specifik omkring hvad der er for en afvigelse du ser?

**Comment by carlk5** [comment]
Tak for oplysningen, kan se det er mig som ikke kunne aflæse oplysninger på eksportpriser.dk korrekt.

Sendt fra min iPad

Den 5. jan. 2023 kl. 10.47 skrev Christian Reinholdt ***@***.***>:

﻿

Jeg har kontrolleret tarifferne som der bliver beregnet efter og de svare overens med dem som N1 oplyser på deres hjemmeside:
https://n1.dk/priser-og-vilkaar<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fn1.dk%2Fpriser-og-vilkaar&data=05%7C01%7C%7C8d944b7a737448beec1108daef01e304%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638085088639136052%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JK8%2BDz40nZzpmSKR0j%2B1xyjL9WLcYlzZxUoNKmWCAxU%3D&reserved=0>

Bemærk at beregningseksemplet på elspotpris.dk kun viser aktive tariffer for den nuværende time. F.eks. er man i lavlast perioden vises kun lavlast tariffen i udregningen.
Dette gøres for at man kan ligge alle tallene sammen i tabellen og så få det korrekte resultat.

Hvis det er noget andet du synes er mærkeligt kan du så ikke blive lidt mere specifik omkring hvad der er for en afvigelse du ser?
