### ISSUE TITLE
Fejl i morgendagens priser

### ISSUE THREAD

**Issue by Thomsen-79** [rndfm/elspotpris#126]
Så vidt jeg kan se passer dagens priser spot on. men det er som om der mangler nogle tariffer i beregningen i priserne for i morgen
![Skærmbillede (159)](https://user-images.githubusercontent.com/61097896/210586517-f114ee2f-23bd-41d5-a212-b917745222b1.png)
iflg mine beregninger får jeg den laveste pris i morgen til 0.4795875kr og ikke 0.19 som oversigten antyder

**Comment by rndfm** [comment]
Tak for reporten. Jeg fik også et hint andetsteds omkring de manglende tariffer for torsdag. 
Jeg fandt fejlen og fremover bør der ikke mangle tariffer for næste dag.

**Comment by Thomsen-79** [comment]
👍🏼 det er super
