### ISSUE TITLE
[TARIFF]

### ISSUE THREAD

**Issue by PerWestphal** [rndfm/elspotpris#127]
Udfyld værdierne i skemaet herunder.
Priserne er i kroner og uden moms.

Udfyld navn, og tariff for lav- og spidslast.

{
    name: "Radius C",
    normal: .3003,
    peak: .7651
}

**Comment by PerWestphal** [comment]
Abonnement hos netselskabet TREFOR El-net A/S ser ud til at være 408,- kr. ekskl. moms i 2023 - er pt. ikke oplyst i jeres "Sådan er prisen pr. kWh udregnet"
https://www.trefor.dk/elnet/priser/

**Comment by rndfm** [comment]
Vi har pt. ikke abonnementer mv fra netselskaberne.
Det har ikke været en prioritet da man alligevel ikke kan vælge at skifte netselskab.

Dog bliver elspotpris.dk mere og mere et oplysningssite og derfor kunne det måske være en ide at vise sådanne oplysninger på et tidspunkt.

**Comment by PerWestphal** [comment]
Hej Christian,

 

Du har ret mht. man ikke kan  skifte netselskab, så når det kun drejer sig om at sammenligne hvilket elselskab der måtte være billigst er det ikke relevant. 

Men når I beregner den aktuelle pris time for time mangler omkostningen til abonnementet til netselskaberne for at give den faktiske pris pr. time – der jo også kun omkring 5 øre så det nok 😊

 

God aften!

Mvh
Per

 

 



 

Fra: Christian Reinholdt ***@***.***> 
Sendt: 5. januar 2023 10:43
Til: rndfm/elspotpris ***@***.***>
Cc: PerWestphal ***@***.***>; State change ***@***.***>
Emne: Re: [rndfm/elspotpris] [TARIFF] (Issue #127)

 

Vi har pt. ikke abonnementer mv fra netselskaberne.
Det har ikke været en prioritet da man alligevel ikke kan vælge at skifte netselskab.

Dog bliver elspotpris.dk mere og mere et oplysningssite og derfor kunne det måske være en ide at vise sådanne oplysninger på et tidspunkt.
