### ISSUE TITLE
[TARIFF]

### ISSUE THREAD

**Issue by DKCroCo** [rndfm/elspotpris#128]
Udfyld værdierne i skemaet herunder.
Priserne er i kroner og uden moms.

Udfyld navn, og tariff for lav- og spidslast.

{
    name: "N1 C",
    normal: .4322,
    peak:  1.0562
}

**Comment by rndfm** [comment]
N1 er der i forvejen?  Og den er automatisk opdateret via datahubben.

**Comment by rndfm** [comment]
Jeg lukker. Du må meget gerne give besked hvis du mener der er noget galt med tariff beregningen på N1.

Bemærk at siden kun viser den aktuelle sats for nuværende time.

**Comment by DKCroCo** [comment]
Jeg havde misset at der kun vises sats for nuværende time. Sorry for misforståelsen. Så helt du lukker den.

**Comment by rndfm** [comment]
Jeg har en opgave på at vise samtlige tariffer over døgnet. Og så på en måde markerer hvilken der er aktiv.
Du er ikke den eneste der er blevet forvirret over det. 

Det skiftede jo også fra at siden viste alle tariffer over døgnet til at den kun viste den aktive. Det skete da jeg overgik fra manuelle opdaterede tariffer til at siden automatisk opdaterer dem fra energinet datahubben.
