### ISSUE TITLE
Ikke muligt at vælge netselskab eller elselskab i Teslas chrominumbrowsher

### ISSUE THREAD

**Issue by ChipMIK1** [rndfm/elspotpris#133]
Som beskrevet i overskriften er det ikke muligt at bruge tilføje netselskab eller elselskab i Teslas Chromium browser.  

Felterne er blanke og der kommer ingen felter frem med de respektive selskaber når felterne berøres.

**Comment by rndfm** [comment]
Skal jeg købe en Tesla for at teste dette? :)

**Comment by ChipMIK1** [comment]
Jeg skal bestemt ikke forhindre dig i det  :-D

**Comment by rndfm** [comment]
Jeg går jo lidt og leder efter en undskyldning for at skifte veteran elbilen ud.(1. gen nissan leaf)

**Comment by ChipMIK1** [comment]
Se så kan du jo takke mig når du har fået den og dette indlæg var spiren til det :-D

**Comment by rndfm** [comment]
https://www.reddit.com/r/TeslaModel3/comments/cc2sya/interesting_bug/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Er det noget ala dette du ser? Kan du evt klare et billede af det?

**Comment by ChipMIK1** [comment]
Det eneste der sker er feltet bliver markeret men der kommer ingen liste med selskaberne. 

![2](https://user-images.githubusercontent.com/40403616/214547018-662c20a2-d7b0-429d-b7c8-189409ee19de.jpg)
![1](https://user-images.githubusercontent.com/40403616/214547023-dbe04125-00f1-437d-9b11-754f352b912b.jpg)

**Comment by rndfm** [comment]
Jeg tror desværre ikke dette er et elspotpris.dk problem men mere et tesla browser problem.

Kan du forsøge at bruge denne fra bilen? http://tesla.emax.dk/dropdown/
Hvis du godt kan bruge andre "almindelige" dropdowns men ikke den på elspotpris.dk så åben meget gerne issuet igen.
