### ISSUE TITLE
Forkert label

### ISSUE THREAD

**Issue by kjaer108** [rndfm/elspotpris#138]
Der er nogle tidsintervaller der er forkerte. Tænker ikke det kan være både 00-17 og 00-24

<html>
<body>

Transportudgifter som betales til dit lokale netselskab - N1 C
--
kl. 00 - 17 | 0,54028 kr.
kl. 00 - 24 | 0,00000 kr.

</body>
</html>

**Comment by rndfm** [comment]
00-24 var den tariff de brugte til rabatten i december. Den spøger åbenbart stadig i datahubben. Dog med 0 kr rabat hele døgnet.

**Comment by rndfm** [comment]
Og ja. Flere netselskaber har tariffer med overlappende tider.

F.eks. har nogle en base tariff og så en spids ovenpå. I stedet for at skifte mellem to.

**Comment by rndfm** [comment]
Jeg har overvejet at skjule 0 kr tariffer

**Comment by rndfm** [comment]
Jeg har nu skjult 0 tariffer
