### ISSUE TITLE
Tillæg for andel timeenergi

### ISSUE THREAD

**Issue by Keldhh** [rndfm/elspotpris#150]
Den står lige nu til ca 5 øre, men jeg mener den er ca 20 øre.

**Comment by rndfm** [comment]
Har vi noget dokumentation for det?

Har du evt. en regning fra dem?

**Comment by Keldhh** [comment]
Beklager, det er ikke korrekt, det jeg rapporterede. Troede jeg så på Andels Timeenergi, men jeg så på Andels variabel pris.Så der er ingen fejl.Mvh KeldDen 22. mar. 2023 kl. 08.58 skrev Christian Reinholdt ***@***.***>:﻿
Har vi noget dokumentation for det?
Har du evt. en regning fra dem?
