### ISSUE TITLE
En forskel på prisen vist på elspotpris.dk eg på app'en elspotpris (Android)

### ISSUE THREAD

**Issue by petergrimstrup** [rndfm/elspotpris#158]
Tak for fremragende app/side!!
Jeg har sat elspotpris.dk til DK1, +Elafgift, +Transmission, +Moms, Konstant C, NRGi-Bevar-Mig-El (mine leverandører)
Jeg har hentet en token i app'en svarende til min leverandøraftale og viser DK1, Med afgift og tarif, Med moms.
Men priserne afviger, idet app'en viser ca 16/20 øre mindre end PC'en, f. eks. tirsdag 4/4-2023:
15-16: 1,55 1,39
16-17: 1,59 1,42
17-18: 2,07 1,87
18-19: 2,30 2,10
19-20: 2,61 2,41
Er der en god forklaring eller hvad gør jeg galt?
Mvh Peter

**Comment by rndfm** [comment]
Forklaringen er nok at det er appen elspotpriser du bruger. Og den har intet med elspotpris.dk at gøre.

Der er lidt rigeligt navneforviring. Jeg arbejder på et nyt navn.

**Comment by rndfm** [comment]
Og forskellen er formentlig at de mangler spotpristillægget fra NRGi

**Comment by petergrimstrup** [comment]
Tak for meget hurtig forklaring!
Og ja, jeg ser jo bare de første tegn af app'ens navn, så jeg troede....
