### ISSUE TITLE
priserne i Vindstød 

### ISSUE THREAD

**Issue by Gobrian1** [rndfm/elspotpris#162]
hej
har lige været inde på Vindstød Dansk Vind og der står følgende
'Din kWh-pris er bundet til markedet for at give dig sikkerhed. Du betaler spotprisen tillagt kun **0,63 øre pr. kWh** og har ikke abonnement. 

det giver et noget andet resultat en 0,00625 
p.s jeg bruger ca.10.000kwh

tak for en super god hjemmeside

Max

**Comment by rndfm** [comment]
Det 0,63 er fordi de runder op på hjemmesiden.

Det er 0,5 øre ex moms. Altså 0,625 øre eller 0,00625 kr :)

*Med venlig hilsen | best regards*
*Christian Reinholdt*
Web-professionel og autodidakt alt-mulig-mand.

tlf. 31718115
***@***.***

**Comment by Gobrian1** [comment]
det giver rigtig god mening havde lige glemt at dividere med 100 :)
