### ISSUE TITLE
Ændring i nettarif c hos netselskabet Elværk

### ISSUE THREAD

**Issue by Thomsen-79** [rndfm/elspotpris#163]
![IMG_6948](https://user-images.githubusercontent.com/61097896/235440986-f01b450f-0c96-4863-863f-a1504170b89f.jpeg)

tror der skal rettes nogle priser

**Comment by rndfm** [comment]
Det ser ud til at energidataservice som leverer data'en ikke har fået nye tariffer med. N1 er også gal.
