### ISSUE TITLE
Transport N1

### ISSUE THREAD

**Issue by Bjarne1352** [rndfm/elspotpris#164]
Hejsa Christian - jeg mener transportprisen burde rettes ned for N1 pr 1 maj ?

**Comment by TaagMan** [comment]
Enig. De er faldet til 40,85 øre incl. moms. https://n1.dk/priser-og-vilkaar

**Comment by rndfm** [comment]
Enig. Problemet er bare at den nye sats ikke er med i dataene fra datahub.

Jeg har skrevet til energidataservice om det er hos dem eller hos N1 fejlen ligger.
