### ISSUE TITLE
Tariffer er forkerte 

### ISSUE THREAD

**Issue by stationsbestyrer** [rndfm/elspotpris#165]
Hej

Tre-for har skiftet til sommer tariffer den 1. maj , men din side er ikke opdateret med de nye tariffer. Vil du se på det ?

Tak for en god side.

Hilsen Christian

**Comment by rndfm** [comment]
Hej.
Ja der er desværre flere af de nye tariffer der mangler i data'en fra energidataservice. Det er fejlmeldt der.

Jeg kunne godt lave en funktion så man kunne lave indtastningerne manuelt. Men jeg vil egentligt hellere at energidataservice får fikset deres fejl.
