### ISSUE TITLE
Nettarif C time

### ISSUE THREAD

**Issue by hchr** [rndfm/elspotpris#170]
Har i glemt at flytte Nettarif C time til sommer tid?
17:00 er for høj (0.2544)
21:00 er for lav (0.0978)
Ser det ud til.

**Comment by rndfm** [comment]
Satserne bliver hentet fra energidataservice. Det er ikke nogen vi vedligeholder manuelt.

Hvilket netselskab snakker vi om?

**Comment by rndfm** [comment]
Ah... nu forstår jeg. Jeg undersøger det lige.

**Comment by rndfm** [comment]
Jeg har lige tjekket med Radius. Det ser rigtigt ud med høj transport fra 17.00-20.59

![image](https://github.com/rndfm/elspotpris/assets/46886958/8cbf8d21-c29e-4ec6-9237-d6b3ddcf607a)

**Comment by hchr** [comment]
Tak. Det er mig der har misforstået tidspunkterne for de høje afgifter :+1:
