### ISSUE TITLE
Tarifmodel 3.0

### ISSUE THREAD

**Issue by cokeman0** [rndfm/elspotpris#174]
Hej,

Jeg har "EL-net kongerslev" som net leverandør. men de transport priser du har (0.50kr) er helt forkert. vi har model 3.0 her i byen. og de er p.t. (Data fra energidataservice.dk)

El-net Kongerslev A/S | 5790002502699 | D03 | C-Tarif | C-Kunder Nettarif | C-Kunder Nettarif efter tarifmodel 3.0 | 2023-06-01 | 2023-10-01 | D02 | 0,242200 | 0,242200 | 0,242200 | 0,242200 | 0,242200 | 0,242200 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,363300 | 0,944500 | 0,944500 | 0,944500 | 0,944500 | 0,363300 | 0,363300 | 0,363300 | 0 | 0 | PT1H

**Comment by rndfm** [comment]
https://github.com/rndfm/elspotpris/commit/ce621d4d9401ffc839654f7c1ed05e5d87545e2b

Kan du tjekke at det ser ud som forventet på siden?

**Comment by cokeman0** [comment]
Løst...

Det virker sku bare :-)

TAK
