### ISSUE TITLE
SpotPrice "plus" 

### ISSUE THREAD

**Issue by MikkelTb** [rndfm/elspotpris#21]
Hi.

This is the bedst and most simple homepage with electrical prices.

But I'm a little bit sad after the last update where the "SpotPrice" contains "afgift" and other stiff.

Normal I use the spot price to se how much I will get for my solar power I send to the grid.

Beside that, you are doing a great job, and keep up with the improvements 😊.

Br Mikkel

**Comment by rndfm** [comment]
Fear not. For you I will bring back the elafgift toggle switch ;)

**Comment by rndfm** [comment]
The "elafgift" switch is back!
