### ISSUE TITLE
Alle tariffer i DK

### ISSUE THREAD

**Issue by eimose** [rndfm/elspotpris#26]
Tariffer findes samlet og opdateret her: https://www.energidataservice.dk/tso-electricity/datahubpricelist

Evt med dette kald:
https://api.energidataservice.dk/dataset/DatahubPricelist?limit=100&filter={%22Note%22:%22Nettarif%20C%20time%22}&start=2022-08-02&end=2022-08-03 (bemærk at dato skal ændres).

**Comment by rndfm** [comment]
Hej

Jeg har godt set dette data punkt. Jeg kom aldrig videre med det da jeg ikke kunne finde f.eks. Radius, Cerius eller for den sags skyld Trefor El-net :)

Måske jeg ikke spørg api'et korrekt?

**Comment by rndfm** [comment]
Okay. Tror jeg måske har fået styr på at spørge api'et korrekt.

Næste problem. Der oplyses kun priser i hele ører. 
F.eks. har radius pt tarif på 30,03 øre. Api'et melder 0,30kr.

**Comment by rndfm** [comment]
Energidataservice returnerer nu korrekte tariffer med flere decimaler. Let's go! 🎉
