### ISSUE TITLE
Clever Power fortjeneste

### ISSUE THREAD

**Issue by soreng** [rndfm/elspotpris#29]
Det er lidt uklart hvor de 0,004kr i fortjeneste hos Clever Power er fra. Selv skriver de at eneste omkostning de pålægger er de 49kr i abonnement.

jeg spørger mest ind til det, da jeg ellers ikke er stødt på det. I eksemplerne betyder det 16/24kr til forskel, så det vælter ikke verden.

**Comment by rndfm** [comment]
Jeg har selv lige regnet den efter med de nyeste indberetninger til elpris.dk - Ser ud til at Clever er ren spotpris nu :)

Jeg retter.
