### ISSUE TITLE
Det ville være rart hvis man i grafen kunne fravælge oplysningerne om CO2, så man alene kunne fokusere på prisen 

### ISSUE THREAD

**Issue by BertelDK** [rndfm/elspotpris#30]

**Comment by rndfm** [comment]
Der kan man faktisk ved at klikke på CO2 og CO2 prognose lige under grafen.

![image](https://user-images.githubusercontent.com/46886958/184703447-99a452ef-695c-40eb-b7d3-2fd10c02b76a.png)

Dog husker siden ikke dette til næste gang man besøger den. Det kunne måske være det som skal til?

**Comment by twikedk** [comment]
Jep, det vil være rart hvis den kan huske indstillingen.

**Comment by rndfm** [comment]
Så huskes indstillingen for visning af CO2 og CO2 prognose.
