### ISSUE TITLE
Clever Power

### ISSUE THREAD

**Issue by ooono-developer** [rndfm/elspotpris#36]
Hejsa

På https://elspotpris.dk/#info

Står der andre omkostninger: 470.40 kr

Hvilke omkostninger er det? Jeg kan ikke se den på mine regninger. 

Venligst opdater oversigten :)

p.s. God service.

**Comment by benne** [comment]
Mit gæt er at der er abonnementet;

39,2 * 12 = 470,40 DKK

**Comment by rndfm** [comment]
Hej. Andre omkostninger dækker i dette tilfælde over(på et år):
12x abonnement: 39,20kr: 470,40 kr. (ex moms)

**Comment by ooono-developer** [comment]
Ahh ja, det giver god mening, tak

Så er der noget andet jeg ikke lige forstår.
Elforbundet står der 32,- i andre omkostninger. Hvad er det så ? For de har jo ikke abonnements udgift.
Men ser man på 'Sådan er prisen udregnet' står der: Betaling via betalingsservice - 8 kr
8*12 = 96,- Det skal vel også regnes med i andre omkostninger?



Ved clever power, sparer man også 100,- per md. hvis man har el bil abo ved siden af.

Så 'andre omkostninger' for mig (da jeg har elbil) er.

49 i abo - 100 i rabat = -51 per måned i andre omkostninger.

Eller -612 om året.

Så Clever power burde vel være med 2 gange, 1 som ren el abo, og en som el abo + el bil abo. ?


Men det er måske en pandoras box, hvis man pludselig skal havde alle særaftaler og rabatter med?

**Comment by benne** [comment]
Mht. Elforbundet, så er mit bud at det er kvartalsmæssig betaling (da det er aconto) - 4 * 8 = 32.

**Comment by ooono-developer** [comment]
Hej Benne

Ja det kunne godt give mening.

Så nogle gange er det per år, og andre gange per md. :(

Jeg er glad for Clever Power ikke er akonto, men per måned bagud ;)

**Comment by rndfm** [comment]
Jeg skal sørge for at der i udregningen kommer information omkring antal betalinger om året på.

**Comment by rndfm** [comment]
Jeg har tilføjet så man kan se hvor mange betalinger om året en udgift er beregnet ud fra.
