### ISSUE TITLE
Identifikation af poster

### ISSUE THREAD

**Issue by Sondergaard51** [rndfm/elspotpris#39]
Vedhæftet elregning.xlsx, som sammenstiller en Q3 à conto betaling til Norlys med poster i elspotpris.dk indstillet til at vise samlet pris for Norlys. Første kolonne er udgiftsposter specificeret af Norlys. Anden kolonne er mit anslåede forbrug. Tredje kolonne er pris pr. kWh angivet med decimal-punkt og fjerde kolonne viser produktet af pris og antal. Femte kolonne sidestiller Norlysposterne med poster i elspotpris.dk. I sjette kolonne er poster sat med fed skrift, hvis de optræder i Norlysposterne. ?? i FEMTE kolonne spørger til, om posterne er korrekt identificerede i Norlysposterne: Er A2 i Norlys det samme som F2. A7 Abonnement netselskab synes ikke i elspotpris.dk's liste. Burde den ikke det?
Tak iø. for et prægtigt initiativ og tak for svar til et fortvivlet forsøg på at forstå elregningen, når man nu kun er vant til at holde styr på patienter på en intensivafdeling.
Med venlig hilsen, Søren Søndergaard
[Elregning.xlsx](https://github.com/rndfm/elspotpris/files/9487673/Elregning.xlsx)

**Comment by rndfm** [comment]
A2 = spotpris + F3 :)

Ja jeg har ikke abonnement med for netselskaber. Det bør nok være med som oplysning.
