### ISSUE TITLE
Grøn el med FDM Strøm

### ISSUE THREAD

**Issue by adamhassel** [rndfm/elspotpris#45]
Udfyld felterne nedenunder.
Alle priser uden moms angiver i kroner.    .15 = 0.15 kr = 15 øre.
Hvis der findes yderligere pristillæg eller gebyrer tilføjes det i samme stil.
Bemærk at udregningen ligger samtlige priser sammen. Vil der gøres opmærksom på en ting som der gratis/ikke betales for kan der laves priser og gebyrer med 0 i "amount".

Hvis der står null ved amount bruges spotprisen.

{
    name: "FDM Strøm",
    prices: [
        {
            name: "spotpris",
            amount: null,
        },
        {
            name: "handelsomkostninger",
            amount: .0025
        },
        {
            name: "grønt tiltag",
            amount: .025
        }
    ],
    fees: [
        {
            name: "abonnement",
            amount: 16
        },
        {
            name: "Indbetalingskort pr. regning",
            amount: 49
        },
        {
            name: "Betalingsservice pr. regning",
            amount: 7.5
        },
        {
            name: "Gebyr ved kundens skift af leverandør i bindingsperiode",
            amount: 500
        },
        {
            name: "Ekstra opgørelse / flytteopgørelse",
            amount: 100
        },
        {
            name: "Kopi af faktura",
            amount: 49
        },
        {
            name: "Rykkergebyr",
            amount: 100
        }
    ]
}

**Comment by adamhassel** [comment]
https://fdm.dk/vi-tilbyder/groen-el-fdm-stroem

https://jyskenergi.dk/el/privat/priser-og-vilkaar/

**Comment by rndfm** [comment]
Takker. Jeg får lagt produktet ind i aften :)

**Comment by rndfm** [comment]
@adamhassel Ved du om det er afregnes aconto eller forbrugsafregnet? (Hvis aconto, hvor lang en periode?)

**Comment by rndfm** [comment]
@adamhassel Og er det samme aftale som https://github.com/rndfm/elspotpris/pull/33 ?
Altså gennem Jysk Energi?

**Comment by adamhassel** [comment]
> @adamhassel Og er det samme aftale som #33 ? Altså gennem Jysk Energi?

Det ligner det, ja.

**Comment by rndfm** [comment]
Så er FDM strøm online på elspotpris.dk

Jeg har tilladt mig at redigerer lidt i priserne efter den linkede side med betingelser. (De fleste var angivet med moms).

Den placerer sig faktisk ret flot i listen :)
![image](https://user-images.githubusercontent.com/46886958/192827617-36bb0779-fe29-4005-800c-5adfcc9fbe78.png)

**Comment by adamhassel** [comment]
> Jeg har tilladt mig at redigerer lidt i priserne efter den linkede side med betingelser. (De fleste var angivet med moms).
)

Det er fint. Det var ikke helt klart udfra din template hvilke priser der var inc og hvilke der var ex moms, men det lyder på dig nu som om det hele skal være ex moms...
