### ISSUE TITLE
Behov for support af netselskab med flere peak-perioder, og startdato for ny tarif

### ISSUE THREAD

**Issue by paf61** [rndfm/elspotpris#47]
Netselslabet Cerius vil fremover have tre tarifintervaller og to årstider:
https://cerius.dk/priser-og-tariffer/prisaendringer/

Der er derfor behov for i prices.js at kunne angive tidsrum og datointerval for hver tarif.
Det kunne også være praktisk at kunne angive kommende tarifændringer med startdato.

Faktisk egner de data sig vist mere til en database, og så kunne man lave så records med forældede takster automatisk bliver slettet - altså records med tariffer der er erstattet af en ny tarif med en startdato der er passeret.

**Comment by rndfm** [comment]
Jeg satser på at lave https://github.com/rndfm/elspotpris/issues/26 her inden den 01/10.

Så laver jeg således at funktionaliteten matcher det data fra energidataservice. Altså 24 satser på et døgn og start/slut datoer.

**Comment by rndfm** [comment]
Denne bliver implicit løst af: https://github.com/rndfm/elspotpris/issues/26
