### ISSUE TITLE
Andel Energi BasisEnergi

### ISSUE THREAD

**Issue by skeptizzle** [rndfm/elspotpris#56]
Udfyld felterne nedenunder.
Alle priser uden moms angiver i kroner.    .15 = 0.15 kr = 15 øre.
Hvis der findes yderligere pristillæg eller gebyrer tilføjes det i samme stil.
Bemærk at udregningen ligger samtlige priser sammen. Vil der gøres opmærksom på en ting som der gratis/ikke betales for kan der laves priser og gebyrer med 0 i "amount".

Priser kan angives med region hvis de er forskellige fra DK1 og DK2.
Angiv både pris for DK1 og DK2.
Hvis prisen er den samme fra begge regioner angives blot en pris uden region på.

{
    name: "Andel Energi BasisEnergi",
    prices: [
            {
                name: "elpris fast DK1",
                amount: 4.8,
                region: "DK1"
            },
            {
                name: "elpris fast DK2",
                amount: 4.8,
                region: "DK2"
            }
    ],
    fees: [
        {
            name: "abonnement",
            amount: 16
        },
        {
            name: "Indbetalingskort pr. regning",
            amount: 49
        },
        {
            name: "Betalingsservice pr. regning",
            amount: 6.25
        },
        {
            name: "Gebyr ved kundens skift af leverandør i bindingsperiode",
            amount: 500
        },
        {
            name: "Ekstra opgørelse / flytteopgørelse",
            amount: 0
        },
        {
            name: "Kopi af faktura",
            amount: 40
        },
        {
            name: "Rykkergebyr",
            amount: 100
        }
    ]
}

**Comment by skeptizzle** [comment]
Vilkår:
https://andelenergi.dk/app/uploads/2022/06/19188_AE_SAP_Std_vilkaar_EL_1juli22_A4_web_100622_inkl_privatliv_5k_Final.pdf
Gebyrer mm. se side 12/26

**Comment by rndfm** [comment]
Som sådan så understøtter platformen også "faste" priser. Men giver det mening?

Et andet problem er vel at ikke alle der har produktet har samme pris da den ændres løbende ved aftaleindgåelsen?
Og så er der hele vedligeholdelsen af fastpris produkter som ændre sig konstant.

Og hvis vi skal begynde at have "faste" priser så skal sammenligningen deles op således at der aldrig kan sammenlignes fastpris produkter med variable produkter.

**Comment by rndfm** [comment]
Jeg lukker denne.

Lad mig vide hvis du er uenig :)

**Comment by skeptizzle** [comment]
@rndfm først beklager jeg det sene svar, det var lidt dårlig stil, men jeg har været lidt hængt op.
Måske giver det ikke mening, min indledende tanke var egentlig at kunne sammenligne fast med variabel, men det kan sagtens være at f.eks. Andel Energi BasisEnergi produktet kan ha' varierende pris fra kunde til kunde. Det troede jeg bare ikke.
Jeg kan sagtens overse komplikationer i forhold til at sammenligne fast og variabel pris. 
Angåede fast pris ville jeg egentlig bare se hvordan prisen inkl. transport og afgifter lå i forhold til variable priser.

Det er ok at du lukker den, jeg finder på en anden måde at regne det ud :)

**Comment by Teddy-Moeller** [comment]
Jeg er også meget interesseret i at få el priser ind i Home Assistant.
Uden at være belemret med viden på området, vil det være muligt at kombinere det med windows' automation funktion? eller en tilsvarende Linux funktion? Ja det kræver en session kørende med windows og en browser. Men indtil en permanent løsning kommer, vil jeg høre om det vil være en "do-able" løsning? (sorry SCRUM master mindset was activated for a few seconds here ;) )
