### ISSUE TITLE
[TARIFF]

### ISSUE THREAD

**Issue by kbh4** [rndfm/elspotpris#58]
Udfyld værdierne i skemaet herunder.
Priserne er i kroner og uden moms.

Udfyld navn, og tariff for lav- og spidslast.

{
    name: "Energi Fyn",
    // kilde: https://www.energifyn.dk/privat/el/spotel/
    normal: .0360,
    peak: .0360
}

**Comment by rndfm** [comment]
Energi Fyn er ikke et netselskab?

**Comment by rndfm** [comment]
Vores elnet er der allerede :)
