### ISSUE TITLE
[PRODUKT]

### ISSUE THREAD

**Issue by kbh4** [rndfm/elspotpris#59]
Udfyld felterne nedenunder.
Alle priser uden moms angiver i kroner.    .15 = 0.15 kr = 15 øre.
Hvis der findes yderligere pristillæg eller gebyrer tilføjes det i samme stil.
Bemærk at udregningen ligger samtlige priser sammen. Vil der gøres opmærksom på en ting som der gratis/ikke betales for kan der laves priser og gebyrer med 0 i "amount".

Hvis der står null ved amount bruges spotprisen.

{
    name: "Energi Fyn - SpotEl",
    link: "https://www.energifyn.dk/privat/el/spotel/"
    prices: [
        {
            name: "spotpris",
            amount: null,
        },
        {
            name: "Abonnement",
            amount: .0810
        },
        {
            name: "Transport",
            amount: .4341
        }
    ],
    fees: [
        {
            name: "Abonnement",
            amount: 12,
            paymentsPerYear: 12
        },
        {
            name: "Betalingsservice pr. regning",
            amount: 4.98
        },
        {
            name: "MobilePay pr. regning",
            amount: 2.6
        }
    ]
}

**Comment by rndfm** [comment]
Transport skal oprettes for sig som netselskab(tariff)
I prices angives det som tillægges spotprisen pr. kWh. Der er normalt ikke abonnement der?

**Comment by kbh4** [comment]
Jeg er kommet til at blande netselskabet ind her. Glem alt om abonnement og transport! ;)

"Fees" står korrekt.

**Comment by rndfm** [comment]
Har energi fyn ikke noget spotpris tillæg?

**Comment by kbh4** [comment]
De har et tillæg på 4,50 øre/kWh - de kalder det "Abonnement":
![image](https://user-images.githubusercontent.com/64138727/195009443-740e3f51-ee2a-46ee-a97c-ee682962ffac.png)

**Comment by rndfm** [comment]
Så i virkeligheden kunne de godt have endnu et tillæg da de viser en SpotEl pris (som kan indeholde tillæg) og så et ekstra i form af "abonnement" ?

**Comment by rndfm** [comment]
Den pris de viser på hjemmesiden har vist ikke rigtigt hold i nogen virkelighed.
Gennemsnitsprisen i september var 254,932 øre pr kWh(Vest).
Så det er svært at gennemskue om de har et skjult tillæg også.

**Comment by rndfm** [comment]
Jeg har opdateret produktet på siden.

Lad mig vide hvis du er uenig :)

**Comment by kbh4** [comment]
Det kunne godt tyde på at det er sådan det hænger sammen - umiddelbart troede jeg at "SpotEl" var lig med spotprisen uden tillæg, men din beregning viser jo noget andet. Jeg prøver lige at kontakte dem, for at se om jeg kan få et endegyldigt svar...

**Comment by kbh4** [comment]
@rndfm - jeg har fået bekræftet fra EnergiFyn, at de tillægger 4 øre/kWh (ex. moms) på Nord Pool spotprisen.

**Comment by rndfm** [comment]
Perfekt. Mange tak :)
 Så fik vi også bekræftet at min baglæns udregning virker;)

**Comment by woopstar** [comment]
> @rndfm - jeg har fået bekræftet fra EnergiFyn, at de tillægger 4 øre/kWh (ex. moms) på Nord Pool spotprisen.

Jeg kan intet finde om dette nogle steder i deres vilkår eller på hjemmesiden. Fik du noget svar på hvor de oplyser det?

**Comment by rndfm** [comment]
Det oplyser det ikke. Og det er desværre ikke ualmindeligt.

**Comment by kbh4** [comment]
Jeg fik det at vide ved at skrive til deres Kundeservice - svaret var "På Spot tillægger vi yderligere 4 øre til Nord Pool prisen. "

**Comment by rndfm** [comment]
Lige nu står det faktisk som et udregnet tillæg på elspotpris.dk. Men det er jo bekræftet.

En der vil lave et pull request på at fjerne "calculated" fra tillægget?

**Comment by woopstar** [comment]
> Det oplyser de ikke. Og det er desværre ikke ualmindeligt.

Vanvittigt nok. Det kan vel næsten ik være lovligt ikke at oplyse det.

Jeg har lavet PR.
