### ISSUE TITLE
Tariffer med flere perioder end spids- og lavlast.

### ISSUE THREAD

**Issue by je1000dk** [rndfm/elspotpris#60]
Udfyld værdierne i skemaet herunder.
Priserne er i kroner og uden moms.

Udfyld navn, og tariff for lav- og spidslast.

{
    name: "TREFOR
![trefor-el-net---priser-pr -1 -januar-2023](https://user-images.githubusercontent.com/115353262/194707660-bebdb93a-3414-455f-98d2-09842684ca29.jpg)
 Vest",
    low: .1392,
    high: .4192,
    peak: 1.2576
}

**Comment by rndfm** [comment]
Inden 1/1 skal vi have understøttet tariffer med flere værdier end spids/lav.

**Comment by rndfm** [comment]
Denne bliver implicit løst af: https://github.com/rndfm/elspotpris/issues/26
