### ISSUE TITLE
[TARIFF] Trefor El-net C (Trekantsområdet)

### ISSUE THREAD

**Issue by kalleguld** [rndfm/elspotpris#62]
Kilde: https://www.trefor.dk/elnet/priser/

Note: nuværende el-net er for Tre-For Øst, dvs. Bornholm.

{
    name: "Trefor El-net C (Trekantsområdet)",
    normal: .2068,
    peak: .5404
}

**Comment by rndfm** [comment]
Så er den tilføjet
