### ISSUE TITLE
elafgift 

### ISSUE THREAD

**Issue by AngelFreak** [rndfm/elspotpris#64]
Det er muligvis mig som har misforstået noget, men er elafgiften ikke 0.763kr, og ikke 0.723 kr som det fremgår af siden ?

**Comment by rndfm** [comment]
Den blev nedsat 4 øre for nyligt?

søn. 16. okt. 2022 09.40 skrev Teis Angel Clausen ***@***.***

**Comment by AngelFreak** [comment]
Følgende er udrag fra skat:

"Fra 1. januar 2022 til 30. juni 2022 udgør elafgiften 90,3 øre pr. kWh. Fra 1. juli 2022 er elafgiften 76,3 øre pr. kWh (90,0 øre pr. kWh i 2021). Bemærk at EU-regler gør, at du ikke får fradrag for de sidste 0,4 øre."

Igen det kan sagtens være mig der har misforstået noget i den måde der er implementeret på. 

https://skat.dk/data.aspx?oid=2234584

**Comment by rndfm** [comment]
Jeg kan godt se at man skal have de helt store google skills igang for at finde det.

Men afgiften blev sænket den 1. Oktober til 72,3 øre.

https://www.ft.dk/samling/20211/almdel/kef/spm/505/svar/1907097/2621231.pdf

**Comment by rndfm** [comment]
Hov. Her er linket.

https://www.skm.dk/skattetal/satser/satser-og-beloebsgraenser-i-lovgivningen/elafgiftsloven/

**Comment by AngelFreak** [comment]
Arghh det kan jeg godt se. 

Tusinde tak for at gøre mig det klogere, og beklager ulejligheden.

Det er et super fedt projekt! Det burde næsten være støttet af public service midler ;)
