### ISSUE TITLE
[TARIFF]

### ISSUE THREAD

**Issue by arnestar** [rndfm/elspotpris#65]
Udfyld værdierne i skemaet herunder.
Priserne er i kroner og uden moms.

Udfyld navn, og tariff for lav- og spidslast.

{
    name: "Elværk ThyMors",
    normal: .3947,
    peak: .12997
}

**Comment by rndfm** [comment]
Det er første netselskab jeg har set hvor peak prisen er lavere end normal prisen :)

Jeg har ændret til:

{
	id: "netselskabet_elvaerk_c",
	name: "Netselskabet Elværk C",
	normal: .3947,
	peak: 1.2997
}

Netselskabet kan nu ses på elspotpris.dk
