### ISSUE TITLE
Hvorfor slutter priserne kl 23:00?

### ISSUE THREAD

**Issue by hekner** [rndfm/elspotpris#74]
Så vidt jeg kan se på Nordpool er priserne tilgængelige helt til kl 24:00 (midnat) næste døgn, så hvorfor stopper grafen ved 23:00?
Er det noget sommer/vintertid der spiller et puds her?

**Comment by hekner** [comment]
I tabel mode vises alle priser hen til kl 00, incl. den sidste time før midnat som mangler i grafmode.. Så fejlen er kun relateret til graf mode og har ikke noget med CET/CEST etc at gøre.

**Comment by rndfm** [comment]
Det er desværre den graf komponent der bruges som laver ged i den.

Jeg har på min todo at skifte komponenten ud.

**Comment by rndfm** [comment]
Første forsøg på en udskiftning af graf komponenten kan nu ses online. Man skal vælge visningen "Bars".


![image](https://user-images.githubusercontent.com/46886958/201544192-4bf0b6bb-f897-409c-9718-5f7a15a79b50.png)

**Comment by hekner** [comment]
Det virker fint - og nu kan man se prisen indtil midnat :-)
Så jeg ville mene at "graf" bare skal pensioneres, og dette issue lukkes?

**Comment by hekner** [comment]
Lukker issue, da den nye "bar" mode fixer issuet og nu er er default
