### ISSUE TITLE
Hvorfor fjerner "elafgift" flueben også balance,system,transmissions nettariffer?

### ISSUE THREAD

**Issue by hekner** [rndfm/elspotpris#75]
Burde den ikke _udelukkende_ fjerne elafgiften? Eller fluebenet burde renames?
At kunne fjerne kun elafgiften med flueben er super brugbart - dels for at se hvad der sker efter 1/1-2023, men også for dem som får leveret strøm uden elafgift (varmepumper etc). 

Så foreslår at ændre det så fluebenet kun styrer elafgiften.
Om man så ønsker endnu et nyt flueben til at kunne styre balance/system/transmissions tarifferne er en anden sag. Men de skal ikke blandes sammen med afgiften.

**Comment by rndfm** [comment]
Godt forslag. Der sørger jeg for kommer med i en version i den nærmeste fremtid:)

**Comment by rndfm** [comment]
Så er elafgift og generel transport blevet separeret :)
