### ISSUE TITLE
Visning af priser med 2 decimaler

### ISSUE THREAD

**Issue by kalleguld** [rndfm/elspotpris#81]
I Danmark vises priser normalt med 2 decimaler, dvs. i Kroner og Ører. Det ser lidt "skævt" ud når der mangler en decimal når prisen er f.eks. 1,90 kr.

Er der stemning for at vise priserne med minimum 2 decimaler? Og med "dansk" decimal-separator?

**Comment by rndfm** [comment]
Det er en glimrende ide :)

Har lavet en enkelt kommentar til pull request'et.

**Comment by kalleguld** [comment]
Jeg kan ikke se kommentaren?

**Comment by rndfm** [comment]
Spøjst.

Men min kommentar gik på hvorfor det var gjort på to forskellige måder.

Et enkelt sted sættes prettyPrice som data. Alle andre steder bruges funktionen til at lave pretty prices bare direkte.
