### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by hetlelid** [rndfm/elspotpris#89]
Tried to install elspotpris on a Docker host using Portainer as new stack. However the installation process can not install "image: rndfm/elspotpris_api" and "image: rndfm/elspotpris_app" since these images are not available as separate images while pulling directly from the web. Any plans to fix this, for an automated installation? I know i could deal with this manually, but on my Synology NAS, i want to avoid this. Preferably the docker image should be hosted on dockerhub. Thank :)

**Comment by rndfm** [comment]
docker build to build the image.

**Comment by rndfm** [comment]
Elspotpris.dk is not meant to be hosted at multiple sites.

**Comment by rndfm** [comment]
If you really want to run elspotpris.dk locally the commands can be found in https://github.com/rndfm/elspotpris/blob/master/.github/workflows/node.js.yml

To make it even easier here are the commands:

cd /var/elspotpris.dk (or wherever you have the source code)
docker build ./elspotpris.app -t rndfm/elspotpris_app
docker build ./elspotpris.api -t rndfm/elspotpris_api
docker compose up -d
