### ISSUE TITLE
Y-aksetitler bør bytte side ve./hø.

### ISSUE THREAD

**Issue by AsgerFrank** [rndfm/elspotpris#91]
Diagrammets Y-akseenheder (g og kr) bør på grund af logik og brugervenlighed bytte side, så det korresponderer med placeringen foroven af Spotpris kr/kWh. resp. CO2 g/kWh.

Akseenhederne burde forresten naturligvis mere korrekt hedde kr/kWh og g/kWh, men hvis hensyn til grafisk indtryk og enkelhed nødvendiggør det, kan man nok fortsat leve med kr og g.

**Comment by rndfm** [comment]
På den nyere visning "søjler" er der netop også byttet rundt på kr og g.

Planen er at udfase den "gamle" graf visning til fordel for den nyere "søjler"

**Comment by rndfm** [comment]
Jeg tillader mig at lukke denne. Håber det er okay? Ellers må du sige til hvis det skal fikses på den gamle graf visning også.
