### ISSUE TITLE
Vindstød VEstrøm

### ISSUE THREAD

**Issue by solmoller** [rndfm/elspotpris#92]
[Vindstød VEstrøm] findes på http://elspotpris.dk/, men ikke længere på Vindstøds hjemmeside

**Comment by rndfm** [comment]
VE strøm kan tilmeldes her.
https://www.vindstoed.dk/tilmelding-vestroem

Det er en rabataftale for solcelle ejere i nogle forummer.

**Comment by rndfm** [comment]
Jeg lukker denne?

**Comment by solmoller** [comment]
Ok, overvej dog at lække linket som kommentar, så produktet kan findes

Mvh Henrik

fre. 2. dec. 2022 09.10 skrev Christian Reinholdt ***@***.***

**Comment by Leifbp** [comment]
hvorfor er der ingen afgift til ni, når man vælger elforbundet som leverandør

**Comment by rndfm** [comment]
> hvorfor er der ingen afgift til N1, når man vælger elforbundet som leverandør

Det har ikke noget med elforbundet at gøre. N1 var gratis i december.
